version: '3.3'
services:
  postgresql:
    image: 'postgres:alpine'
    restart: 'always'
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
volumes:
  postgresql_data:
    driver: 'local'