version: '3.3'
services:
  postgresql:
    image: 'postgres:14-alpine'
    restart: 'on-failure'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
volumes:
  postgres-data:
    driver: 'local'