# System Configuration
server:
  port: 8888
  servlet:
    context-path: /practice-01/api
logging:
  level:
    com:
      studevs:
        practice:
          practice01: DEBUG

# Database Configuration
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Custom Configuration
custom:
  db:
    initialize:
      test-data: true